apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: dockerdemo1-rs
  labels:
    app: dockerdemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dockerdemo
  template:
    metadata:
      name: dockerdemo
      labels:
        app: dockerdemo
    spec:
      containers:
        - name: dockerdemo
          image: srinivas350/dockimage
          imagePullPolicy: IfNotPresent
      restartPolicy: Always